sudo: false
dist: trusty
language: rust
matrix:
  include:
    - rust: nightly
script:
  - cargo update
  - cargo build
  - cargo test
cache:
  cargo: true
before_cache:
  - chmod -R a+r $HOME/.cargo
