[package]
name = "svg2gcode"
version = "0.0.1"
authors = ["Sameer Puri <purisame@spuri.io>"]
edition = "2018"
description = "Convert paths in SVG files to GCode for a pen plotter or laser engraver"

[dependencies]
lyon_geom = "0"
clap = "2"
log = "0"
env_logger = "0"
uom = "0.31.0"
paste = "0"
roxmltree = "0"
svgtypes = "0"
petgraph = "0"
